FROM python:2.7.17-alpine3.11

RUN apk update && apk add git && pip install update 
RUN git clone https://github.com/vysecurity/LinkedInt.git && cd /LinkedInt && sed -i '/pkg-resources==0.0.0/d' requirements.txt && pip install -r requirements.txt 

WORKDIR /LinkedInt 

ENTRYPOINT ["python", "LinkedInt.py"]

