FROM python:2.7-alpine

RUN apk update && apk add git
RUN git clone https://github.com/BishopFox/spoofcheck && cd /spoofcheck &&  pip install -r requirements.txt 

WORKDIR /spoofcheck

ENTRYPOINT ["python", "spoofcheck.py"]

