FROM python:2.7.17-alpine3.11

RUN apk update && apk add git && pip install update 
RUN git clone https://github.com/BishopFox/spoofcheck && cd /spoofcheck &&  pip install -r requirements.txt 

WORKDIR /spoofcheck

ENTRYPOINT ["python", "spoofcheck.py"]

